server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: test-microservice
management:
  endpoints:
    web:
      exposure:
        include:
          - 'info'
