security:
  jwt:
    token:
      secretKey: 53cr3753cr3753cr3753cr3753cr3753cr3753cr3753cr3753cr3753cr37
      validityInMilliseconds: 86400000
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: auth-microservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_microservice?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    flyway:
      url: jdbc:mysql://localhost:3306
      schemas:
        - auth_microservice
      user: root
      password: 1234
